#!/bin/sh
# live-build configuration script
# see 'man lb config'

lb config noauto \
--apt-recommends false \
--apt-source-archives false \
--apt-indices false \
--architectures amd64 \
--archive-areas 'main contrib non-free non-free-firmware' \
--backports true \
--security true \
--updates true \
--source false \
--binary-filesystem ext4 \
--binary-images hdd \
--checksums none \
--clean \
--debconf-frontend noninteractive \
--debian-installer none \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--distribution bookworm \
--firmware-binary true \
--firmware-chroot true \
--initramfs live-boot \
--linux-packages "linux-image linux-headers" \
--bootappend-live "boot=live config quiet splash hostname=SpiralLinux" \
--memtest memtest86+x64 \
--win32-loader false

"${@}"
