@startwbs

* <:palm_tree:> includes.chroot
** <:palm_tree:> usr
*** <:palm_tree:> share
**** <:palm_tree:> polkit-1
***** <:palm_tree:> actions
****** <:four_leaf_clover:> snapper-gui-root.policy
****** <:four_leaf_clover:> dpkg-reconfigure-locales.policy
****** <:four_leaf_clover:> gnome-software-root.policy
****** <:four_leaf_clover:> plasma-discover-root.policy
**** <:palm_tree:> grub-btrfs
***** <:palm_tree:> initramfs
****** <:palm_tree:> Arch Linux
******* <:four_leaf_clover:> overlay_snap_ro-hook
******* <:four_leaf_clover:> overlay_snap_ro-install
***** <:palm_tree:> temp
****** <:four_leaf_clover:> grub-btrfs.8
****** <:four_leaf_clover:> grub-btrfsd.8
***** <:four_leaf_clover:> grub-btrfsd
***** <:four_leaf_clover:> grub-btrfsd.initd
***** <:four_leaf_clover:> grub-btrfsd.service
***** <:palm_tree:> manpages
****** <:four_leaf_clover:> grub-btrfsd.8.org
****** <:four_leaf_clover:> grub-btrfsd.8.man
****** <:four_leaf_clover:> grub-btrfs.8.org
****** <:four_leaf_clover:> grub-btrfs.8.man
***** <:four_leaf_clover:> grub-btrfsd.confd
***** <:four_leaf_clover:> 41_snapshots-btrfs
***** <:four_leaf_clover:> config
**** <:palm_tree:> sddm
***** <:palm_tree:> themes
****** <:palm_tree:> breeze
******* <:four_leaf_clover:> theme.conf.user
**** <:palm_tree:> wallpapers
**** <:palm_tree:> applications
***** <:four_leaf_clover:> snapper-gui-root.desktop
***** <:four_leaf_clover:> language-support.desktop
***** <:four_leaf_clover:> exposicion.desktop
***** <:four_leaf_clover:> plasma-discover-root.desktop
*** <:palm_tree:> sbin
**** <:four_leaf_clover:> language-support.sh
**** <:four_leaf_clover:> sources-final
**** <:four_leaf_clover:> reconfigure-locales-wrapper.sh
**** <:four_leaf_clover:> snapper-rollback
**** <:four_leaf_clover:> bootloader-config
*** <:palm_tree:> lib
**** <:palm_tree:> live
***** <:palm_tree:> config
****** <:four_leaf_clover:> 1160-openssh-server
**** <:palm_tree:> systemd
***** <:palm_tree:> system
****** <:four_leaf_clover:> regenerate_ssh_host_keys.service
*** <:palm_tree:> bin
**** <:four_leaf_clover:> install-debian
** <:palm_tree:> etc
*** <:palm_tree:> fonts
**** <:palm_tree:> conf.d
***** <:four_leaf_clover:> 68-color-emoji.conf
***** <:four_leaf_clover:> 20-no-embedded.conf
***** <:four_leaf_clover:> 42-antialias.conf
***** <:four_leaf_clover:> 11-lcdfilter-default.conf
**** <:palm_tree:> conf.avail
***** <:four_leaf_clover:> 11-lcdfilter-default.conf
***** <:four_leaf_clover:> 42-antialias.conf
***** <:four_leaf_clover:> 20-no-embedded.conf
***** <:four_leaf_clover:> 68-color-emoji.conf
*** <:palm_tree:> pipewire
**** <:palm_tree:> pipewire-pulse.conf.d
***** <:four_leaf_clover:> SpiralLinux_pipewire-pulse.conf
**** <:palm_tree:> pipewire.conf.d
***** <:four_leaf_clover:> SpiralLinux_pipewire.conf
*** <:palm_tree:> sudoers.d
**** <:four_leaf_clover:> secure_path
**** <:four_leaf_clover:> pwfeedback
**** <:four_leaf_clover:> timeout
*** <:palm_tree:> live
**** <:four_leaf_clover:> config.conf
**** <:four_leaf_clover:> tools.conf
*** <:palm_tree:> NetworkManager
**** <:palm_tree:> dnsmasq.d
***** <:four_leaf_clover:> options
**** <:palm_tree:> conf.d
***** <:four_leaf_clover:> localdns.conf
*** <:palm_tree:> dconf
**** <:palm_tree:> db
***** <:palm_tree:> local.d
**** <:palm_tree:> profile
***** <:four_leaf_clover:> user
*** <:palm_tree:> skel
**** <:palm_tree:> Desktop
***** <:four_leaf_clover:> language-support.desktop
*** <:palm_tree:> security
**** <:palm_tree:> limits.d
***** <:four_leaf_clover:> 99-SpiralLinux-audio-limits.conf
*** <:palm_tree:> apt
**** <:palm_tree:> apt.conf.d
***** <:four_leaf_clover:> 99norecommends
***** <:four_leaf_clover:> no-bookworm-firmware-message.conf
***** <:four_leaf_clover:> 01nocache
**** <:palm_tree:> preferences.d
***** <:four_leaf_clover:> 99backports
**** <:palm_tree:> sources.list.d
*** <:palm_tree:> pam.d
**** <:four_leaf_clover:> lightdm
*** <:palm_tree:> calamares
**** <:palm_tree:> modules
***** <:four_leaf_clover:> machineid.conf
***** <:four_leaf_clover:> fstab.conf
***** <:four_leaf_clover:> removeuser.conf
***** <:four_leaf_clover:> unpackfs.conf
***** <:four_leaf_clover:> services-systemd.conf
***** <:four_leaf_clover:> finished.conf
***** <:four_leaf_clover:> mount.conf
***** <:four_leaf_clover:> users.conf
***** <:four_leaf_clover:> welcome.conf
***** <:four_leaf_clover:> displaymanager.conf
***** <:four_leaf_clover:> luksopenswaphookcfg.conf
***** <:four_leaf_clover:> packages.conf
***** <:four_leaf_clover:> shellprocess.conf
***** <:four_leaf_clover:> partition.conf
***** <:four_leaf_clover:> bootloader.conf
***** <:four_leaf_clover:> grubcfg.conf
**** <:palm_tree:> branding
***** <:palm_tree:> debian
****** <:four_leaf_clover:> branding.desc
****** <:four_leaf_clover:> show.qml
**** <:four_leaf_clover:> settings.conf
*** <:palm_tree:> default
**** <:four_leaf_clover:> keyboard
**** <:four_leaf_clover:> zramswap
*** <:palm_tree:> polkit-1
**** <:palm_tree:> rules.d
***** <:four_leaf_clover:> 99-cups-admin-no-password.rules
*** <:four_leaf_clover:> snapper-rollback.conf
*** <:palm_tree:> udev
**** <:palm_tree:> rules.d
***** <:four_leaf_clover:> 99-cpu-dma-latency.rules
*** <:palm_tree:> systemd
**** <:palm_tree:> network
**** <:palm_tree:> system
***** <:four_leaf_clover:> cpupower.service
*** <:palm_tree:> X11
**** <:palm_tree:> xorg.conf.d
***** <:four_leaf_clover:> 40-libinput.conf
*** <:palm_tree:> wireplumber
**** <:palm_tree:> policy.lua.d
***** <:four_leaf_clover:> 11-bluetooth-policy.lua
*** <:palm_tree:> sysctl.d
**** <:four_leaf_clover:> 99-SpiralLinux.conf
*** <:palm_tree:> xdg
**** <:palm_tree:> autostart
***** <:four_leaf_clover:> calamares-desktop-icon.desktop
***** <:four_leaf_clover:> xdg-user-dirs-kde.desktop
*** <:four_leaf_clover:> updatedb.conf
*** <:four_leaf_clover:> environment
*** <:palm_tree:> modprobe.d
**** <:four_leaf_clover:> blacklist-pcspkr.conf
*** <:four_leaf_clover:> sddm.conf
*** <:palm_tree:> plymouth
**** <:four_leaf_clover:> plymouthd.conf
** <:palm_tree:> root
** <:palm_tree:> boot
*** <:palm_tree:> grub
** <:palm_tree:> lib
*** <:palm_tree:> live
**** <:palm_tree:> config
***** <:four_leaf_clover:> 2000-spirallinux

@endwbs